- // MIR for `example` before DestinationPropagation
+ // MIR for `example` after DestinationPropagation
  
  fn example() -> () {
      let mut _0: ();
      let mut _1: Foo;
      let _2: ();
      let mut _3: *mut Foo;
      let _5: ();
      let mut _6: *mut Foo;
      scope 1 {
          debug a => _1;
          let mut _4: Foo;
          scope 2 {
-             debug b => _4;
+             debug b => _1;
          }
      }
  
      bb0: {
-         StorageLive(_1);
+         nop;
          _1 = foo() -> [return: bb1, unwind continue];
      }
  
      bb1: {
          StorageLive(_2);
          StorageLive(_3);
          _3 = &raw mut _1;
          _2 = observe::<Foo>(move _3) -> [return: bb2, unwind continue];
      }
  
      bb2: {
          StorageDead(_3);
          StorageDead(_2);
-         StorageLive(_4);
-         _4 = move _1;
+         nop;
+         nop;
          StorageLive(_5);
          StorageLive(_6);
-         _6 = &raw mut _4;
+         _6 = &raw mut _1;
          _5 = observe::<Foo>(move _6) -> [return: bb3, unwind continue];
      }
  
      bb3: {
          StorageDead(_6);
          StorageDead(_5);
          _0 = const ();
-         StorageDead(_4);
-         StorageDead(_1);
+         nop;
+         nop;
          return;
      }
  }
  
