- // MIR for `issue_77355_opt` before JumpThreading
+ // MIR for `issue_77355_opt` after JumpThreading
  
  fn issue_77355_opt(_1: Foo) -> u64 {
      debug num => _1;
      let mut _0: u64;
      let mut _2: bool;
      let mut _3: isize;
  
      bb0: {
          StorageLive(_2);
          _3 = discriminant(_1);
          switchInt(move _3) -> [1: bb2, 2: bb2, otherwise: bb1];
      }
  
      bb1: {
          _2 = const false;
-         goto -> bb3;
+         goto -> bb7;
      }
  
      bb2: {
          _2 = const true;
          goto -> bb3;
      }
  
      bb3: {
-         switchInt(move _2) -> [0: bb5, otherwise: bb4];
+         goto -> bb4;
      }
  
      bb4: {
          _0 = const 23_u64;
          goto -> bb6;
      }
  
      bb5: {
          _0 = const 42_u64;
          goto -> bb6;
      }
  
      bb6: {
          StorageDead(_2);
          return;
+     }
+ 
+     bb7: {
+         goto -> bb5;
      }
  }
  
